Farm prices bugfix
ApeSwapFinance/apeswap-frontend pull request #698
Opened 2021-12-13 03:22 UTC by fedestraus

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2021-12-16 13:17 UTC, fedestraus commented
Hello fellow Apes,

In this commit the LP pricing uses the multicallfetching with a similar function than the token prices (I have to create a new one though because I changed the previous a little bit).

For the config file (lpPrices.ts) I assumed that:

1) all LP Tokens have 18 decimals
2) farm pid with no name are deprecated or not used, therefore I did not copy them.

Let me know your thoughts.

Regards

Fede

2021-12-16 23:44 UTC, ape-swap commented on src/hooks/api.ts
> +  return data;
Thanks a lot for your contribution!

Should we delete this unused piece of code?

2021-12-17 12:15 UTC, fedestraus commented on src/hooks/api.ts
> +  return data;
It won't be used indeed. I already deleted it for you.

My apologies!

Cheers

Fede

2021-12-30 00:01 UTC, Harambe-Nakamoto requested changes
Nice work! Would it be possible for you to extend the original tokenPrices code to handle LP tokens with a separate call? There is a lot of code you could reuse with that.

2021-12-30 01:40 UTC, fedestraus commented
> Nice work! Would it be possible for you to extend the original tokenPrices code to handle LP tokens with a separate call? There is a lot of code you could reuse with that.

I didn't want to change the original tokenPrices function. But I completely agree with your comment. Will make the changes and commit them ASAP

2021-12-30 14:29 UTC, fedestraus commented
I've refactored the fetch prices function to handle both tokens and Lp tokens fetch pricing.

Let me know your thoughts on that and tell me if this fulfills your request.

Fede

2021-12-31 16:46 UTC, ape-swap commented on src/hooks/api.ts
> +  return data;
Thanks!

2022-01-03 02:12 UTC, Harambe-Nakamoto requested changes
Could you leave the lpPrice call out of the farms state and use the same technique as tokenPrices? Pretty much what you had before, but reusing the tokenPrice calls. You can grab the LP address from the farm config instead of creating another file for them. Let me know if that makes sense.

2022-01-08 01:32 UTC, Harambe-Nakamoto requested changes
Nice work! Just one last small change and its good to go.

2022-01-08 01:32 UTC, Harambe-Nakamoto commented on src/state/lpPrices/fetchLpPrices.ts
> +    const tokenDecimals = await multicall(multicallContract, erc20ABI, erc20Calls)
We actually dont need to fetch token decimals for LPs because they will be 18 decimals

2022-01-08 23:19 UTC, Harambe-Nakamoto approved these changes

2022-01-09 12:51 UTC, merged