IAO Revamp for LinearVesting method support
ApeSwapFinance/apeswap-frontend pull request #746
Opened 2022-01-04 03:18 UTC by apewukong

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

- Implement the new design for IAO page
- Support IAO LinearVesting

2022-01-04 13:38 UTC, apewukong commented on src/views/ApeZone/Zone.tsx
> -      <Divider />
Agreed with Obie to remove this section as we want to focus on IAO fully through IAO page, and also with the new design update, this UI needs further updates

2022-01-04 13:38 UTC, apewukong commented on src/views/ApeZone/components/IAO/CurrentIao.tsx
>  import Title from '../Description/Title'
This `CurrentIAO` component is currently not used, as it's removed in `src/views/ApeZone/Zone.tsx`

2022-01-04 13:44 UTC, apewukong commented on src/views/Ifos/components/IfoCard/FourPhaseVesting/index.tsx
> +          name: 'getTotalStakeTokenBalance', // TODO: This value is decreased after the offering, not a real value for the raised amount
Would like to hear your thoughts: @Harambe-Nakamoto @DeFiFoFum

2022-01-04 13:44 UTC, apewukong commented on src/views/Ifos/components/IfoCard/LinearVesting/index.tsx
> +        { label: 'Tokens vested', value: Number(userTokenStatus.offeringTokensVested).toString() },
If I understood this section - "Tokens vested" correctly, it's the amount of the tokens vested up until the current time?

If that's the right, this value is supposed to be updated and increased on every second? @obiedobo @Harambe-Nakamoto .. cc @DeFiFoFum

2022-01-04 14:59 UTC, apewukong commented on src/views/Ifos/components/IfoCard/FourPhaseVesting/index.tsx
> +          name: 'getTotalStakeTokenBalance', // TODO: This value is decreased after the offering, not a real value for the raised amount
Update: replaced this with `totalAmount`

2022-01-04 16:07 UTC, Harambe-Nakamoto commented on src/views/ApeZone/Zone.tsx
> -      <Divider />
Agree

2022-01-06 23:50 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/ContributeInput/ContributeInput.tsx
> +  }
Could you move web3 calls to their own file? Check out the hooks folder on iazos.

2022-01-06 23:53 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/FourPhaseVesting/IfoCardContribute.tsx
> +import { Contract } from 'web3-eth-contract'
Same web3 calls to move here as well

2022-01-07 00:00 UTC, Harambe-Nakamoto requested changes
Nice work Wukong!

2022-01-07 17:46 UTC, apewukong commented on src/views/Ifos/components/IfoCard/ContributeInput/ContributeInput.tsx
> +  }
Yeah, I've done this

2022-01-14 17:45 UTC, Harambe-Nakamoto commented on src/utils/web3React.ts
> +export const connectorsByName: { [connectorName in ConnectorNames]?: any } = {
Is there a specific reason for this?

2022-01-14 17:46 UTC, apewukong commented on src/utils/web3React.ts
> +export const connectorsByName: { [connectorName in ConnectorNames]?: any } = {
Yes. Otherwise, i need to provide connector for ConnectorNames.WALLETLINK, which I'm not sure.

2022-01-14 17:56 UTC, Harambe-Nakamoto commented on src/views/Ifos/hooks/useLinearIAOHarvest.ts
> +  const { account } = useWeb3React()
Can you bring in chainId from here rather than the config

2022-01-14 17:56 UTC, Harambe-Nakamoto commented on src/views/Ifos/hooks/useIAODeposit.ts
> +  const { account } = useWeb3React()
Can you bring chainId in through here rather than the config

2022-01-14 17:57 UTC, Harambe-Nakamoto commented on src/views/Ifos/hooks/useFourPhaseIAOHarvest.ts
> +  const { account } = useWeb3React()
Same chainId issue here

2022-01-14 18:44 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/FourPhaseVesting/index.tsx
> +    }
You dont need to change this now, but for future implementations lets try to keep web3 calls and state management in redux

2022-01-14 18:46 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/FourPhaseVesting/useUserInfo.ts
> +      ]
Same web3 comment here. You dont need to change this now, but it is cleaner to keep these in the state folder

2022-01-14 18:47 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/LinearVesting/index.tsx
> +      ]
Same thing here

2022-01-14 18:47 UTC, Harambe-Nakamoto commented on src/views/Ifos/components/IfoCard/LinearVesting/useUserInfo.ts
> +      ]
Same here as well

2022-01-14 18:48 UTC, Harambe-Nakamoto approved these changes

2022-01-20 00:32 UTC, merged