Nfbs profile james
ApeSwapFinance/apeswap-frontend pull request #787
Opened 2022-01-28 12:13 UTC by jamesbane

1. If user has NFA, display rarest NFA (as it currently does)
2. If user does not have NFA, check for NFBs. If user has NFB, display NFB.
3. If users does not have NFA or NFB, use placeholder avatar like currently displayed

2022-02-03 16:27 UTC, Harambe-Nakamoto commented on src/state/profile/getProfile.ts
> +import { getContract } from 'utils/web3'
Could you switch this to utils/getContract. It pulls from the ethers library instead of web3. We are in the process of deprecating all web3 contracts

2022-02-03 16:29 UTC, jamesbane commented on src/state/profile/getProfile.ts
> +import { getContract } from 'utils/web3'
Okay I will switch to ethers Contract

2022-02-03 16:29 UTC, Harambe-Nakamoto commented on src/state/profile/getProfile.ts
> -    const nfasOwned = address ? await nfaContract.balanceOf(address) : '0'
Once you switch it back to Ethers this will be the correct call

2022-02-03 16:30 UTC, jamesbane commented on src/state/profile/getProfile.ts
> -    const nfasOwned = address ? await nfaContract.balanceOf(address) : '0'
yes sure

2022-02-03 16:30 UTC, Harambe-Nakamoto commented on src/views/NfaStaking/components/DepositModal.tsx
> +  // @ts-ignore
What happened here?

2022-02-03 16:31 UTC, Harambe-Nakamoto requested changes
Nice work! I left a few comments

2022-02-03 16:32 UTC, jamesbane commented on src/views/NfaStaking/components/DepositModal.tsx
> +  // @ts-ignore
ownedNfts is null for nfb profile.

2022-02-03 16:34 UTC, Harambe-Nakamoto commented on src/views/NfaStaking/components/DepositModal.tsx
> +  // @ts-ignore
I mean the @ts-ignore

2022-02-03 16:35 UTC, jamesbane commented on src/views/NfaStaking/components/DepositModal.tsx
> +  // @ts-ignore
let me check

2022-02-03 16:35 UTC, jamesbane commented on src/views/NfaStaking/components/DepositModal.tsx
> +  // @ts-ignore
I can remove ts-ignore.

2022-02-09 16:43 UTC, Harambe-Nakamoto approved these changes

2022-02-09 17:02 UTC, merged